esphome:
  name: creality-pi-space-plus
  friendly_name: Creality Pi Space Plus
  includes:
    - i2c_sniffer.h

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "your_api_key" #change

ota:
  - platform: esphome
    password: "your_password" #change

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Creality-Pi-Space-Plus"
    password: "yourpassword" #change

web_server:
  port: 80
captive_portal:
    

globals:
  - id: i2c_scl_pin
    type: int
    initial_value: '22' 
  - id: i2c_sda_pin
    type: int
    initial_value: '21' 

sensor:
  - platform: template
    name: "Set Temperature"
    id: set_temp
    unit_of_measurement: "°C"
    accuracy_decimals: 0
    
  - platform: template
    name: "Current Temperature"
    id: current_temp
    unit_of_measurement: "°C"
    accuracy_decimals: 0
    
  - platform: template
    name: "Humidity"
    id: humidity
    unit_of_measurement: "%"
    accuracy_decimals: 0

text_sensor:
  - platform: template
    name: "Drying Time"
    id: drying_time
    
  - platform: template
    name: "Material"
    id: material
    
  - platform: template
    name: "Cursor State"
    id: cursor_state
    
  - platform: template
    name: "Temperature Units"
    id: temp_units

  - platform: template
    name: "Dryer Status"
    id: dryer_status
    icon: "mdi:power-cycle"


custom_component:
  - lambda: |-
      auto sniffer = new I2CSniffer();
      return {sniffer};


switch:
  - platform: gpio
    pin: 
      number: GPIO16 
    name: "Power"
    id: button_power
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 1000ms      
      - switch.turn_off: button_power

  - platform: gpio
    pin: 
      number: GPIO17 
    name: "Up"
    id: button_up
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 100ms
      - switch.turn_off: button_up

  - platform: gpio
    pin: 
      number: GPIO27
    name: "Down"
    id: button_down
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: button_down

  - platform: gpio
    pin: 
      number: GPIO25
    name: "Set / Cursor"
    id: button_set
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 100ms
      - switch.turn_off: button_set





    

